services:
  ia_create_venv:
    hostname:         ia_create_venv.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_create_venv:latest
    #    -           ia_create_venv:latest
    #    - innovanon/ia_create_venv
    #    -           ia_create_venv
    image:            innovanon/ia_create_venv
    restart:          no
    logging:
      driver:         syslog   
