services:
  ia_create_venv:
    hostname:         ia_create_venv.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_create_venv:latest
    restart:          no
    logging:
      driver:         syslog   
